source 'https://github.com/CocoaPods/Specs'

platform :ios, '11.0'

use_frameworks!
inhibit_all_warnings!

def common_pods
	pod 'SnapKit'
  	pod 'RxSwift', '~> 4.5'
  	pod 'RxCocoa', '~> 4.5'
  	pod 'RxDataSources', '~> 3.0'
  	pod 'Firebase/Core', :inhibit_warnings => true
  	pod 'Firebase/Database', :inhibit_warnings => true
  	pod 'Firebase/Auth', :inhibit_warnings => true
  	pod 'GoogleSignIn', :inhibit_warnings => true
  	pod 'FBSDKLoginKit', '4.42.0', :inhibit_warnings => true
  	pod 'FBSDKCoreKit', '4.42.0'
 	pod 'FacebookCore', '0.5.0'
  	pod 'FacebookLogin', '0.5.0'
  	pod 'IQKeyboardManagerSwift', '6.3.0'end

def test_pods
	pod 'RxTest', '~> 4'
end

target 'Rx_MVVM_ToDoList' do
	project 'Rx_MVVM_ToDoList'
	common_pods

	target 'Rx_MVVM_ToDoListTests' do
		test_pods
        inherit! :search_paths
	end 

	target 'Rx_MVVM_ToDoListUITests' do
		common_pods 
		test_pods
		inherit! :search_paths
	end
end
